services:
  wikiproxy:
    container_name: wikiproxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3672:3672"

networks:
  default:
    driver: bridge
    name: pangolin
    external: true
