[project]
name = "wikiproxy"
dynamic = ["version"]
description = "A FutureRestore-compatible firmware key API."
authors = [
    {name = "m1stadev", email = "adamhamdi31@gmail.com"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.21.1",
    "uvicorn[standard]>=0.40.0",
    "loguru>=0.7.3",
    "plykos>=0.3",
    "fastapi[standard]>=0.128.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]

[project.urls]
Repository = "https://github.com/m1stadev/wikiproxy"
"Bug Tracker" = "https://github.com/m1stadev/wikiproxy/issues"

[project.scripts]
wikiproxy = "wikiproxy.__main__:app"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.poetry-dynamic-versioning]
vcs = "git"
style = "semver"
dirty = true

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E722"]

[tool.ruff.format]
quote-style = "preserve"
